
# First thing to configure is what endpoints should our cache forward requests to.
# If your cache is running on https://api.acme.com/api/graphql then you should set the following:
# origin="https://api.acme.com/api/graphql"

origin="http://localhost:8080/graphql"


# Next, we need to configure the port that our cache will run on.
# If you want to run the cache on port 8080, set the following:
# port=8080

port=9090


# We also need to configure the cache backend, do you want to cache the values in memory or in redis. Currently only in memory and redis is supported. Here is a list of supported values for cache_backend:
# redis
# in_memory

cache_backend="in_memory"

[redis]
host="localhost"
port=6379


# If you want to override the API paths for the cache server, you can configure them here.

[handlers]
# flush_all_path="/flush"
# flush_by_type_path="/flush.type"
# debug_path="/debug"
# health_path="/health"
# graphql_path="/graphql"