
# First thing to configure is what endpoints should our cache forward requests to.
# If your cache is running on https://api.acme.com/api/graphql then you should set the following:
# origin="https://api.acme.com/api/graphql"

origin="http://localhost:8080/graphql"


# Next, we need to configure the port that our cache will run on.
# If you want to run the cache on port 8080, set the following:
# port=8080

port=9090


# The returns cache hit or cache miss in the header you specify here. Default is X-Orbit-Cache
# cache_header_name="X-Orbit-Cache"

# TTL of the graphql cache in seconds - default is 60 minutes
# cache_ttl=3600

# If you have an authenticated API and want to separate the cache based on what the headers are, you can configure the headers here.
# The system will scope the cache based on the unique values of the headers you provide
# For example, if you want to scope the cache based on the Authorization header, you can set the following:
# scope_headers=[ "Authorization", "X-API-Key" ]


# the field in your graphql responses we should use to identify unique objects (your primary key), this defaults to id
# If you want to use the field "uuid" as the primary key, you can set the following:
# primary_key_field="id"


# log format is the format you want the system to log in, supported values are "json" and "text", it defaults to "text"
# log_format="text"

# log level is the level of logging you want to see, supported values are "debug", "info", "warn", "error", it defaults to "info"
# log_level="info"

# We also need to configure the cache backend, do you want to cache the values in memory or in redis. Currently only in memory and redis is supported. Here is a list of supported values for cache_backend:
# redis
# in_memory

# cache_backend="in_memory"
# redis_host="localhost"
# redis_port=6379


# If you want to override the API paths for the cache server, you can configure them here.
# handlers_flush_all_path="/flush"
# handlers_flush_by_type_path="/flush.type"
# handlers_debug_path="/debug"
# handlers_health_path="/health"
# handlers_graphql_path="/graphql"