// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodoParams struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}
