# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: |
            go.sum

      - name: Start Todo API
        uses: JarvusInnovations/background-action@v1
        with:
          run: go run test_api/todo/server.go
          wait-on: |
            http://localhost:8080
          tail: true
          wait-for: 30s
          log-output-if: failure

      - name: Start Cache API
        uses: JarvusInnovations/background-action@v1
        with:
          run: go run main.go
          wait-on: |
            http://localhost:9090
          tail: true
          wait-for: 30s
          log-output-if: failure

      - name: Run Tests
        run: |
          go test -v ./...
