# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  RunTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: |
            go.sum

      - name: Launch Test Server (todo)
        run: go run test_api/todo/server.go & sleep 5

      - name: Launch Cache Server
        run: go run main.go & sleep 5

      - name: Run Test
        run: go test -v ./...
